# Generated by Django 4.1.3 on 2024-05-17 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_projectimage'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
